Synth\NotificationBundle\Entity\Notification:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    message:
      type: text
    read:
      type: boolean
    createdAt:
      type: datetimetz
  lifecycleCallbacks: {  }
