services:
  synth_notification.mailer.default:
    class: %synth_notification.mailer_class%
    arguments:
      - @mailer
      - @router
      - @templating
      - new_notification.template: test
        from_email:
          address: dom@synthmedia.co.uk